### ISSUE TITLE
Opcode IN

### ISSUE THREAD

**Issue by nic24-rgb** [taylorza/zxn-inlineasm-doc#3]
I have the following code:
`LD BC, 0DDEh`
`IN A, (C)`
`AND %00000010`
`JR Z, SUBROUTINE`

currently undefined symbol for IN A, (C) line results.
If C is changed to IN A, (0DEh) then 'divide by zero' on the next line is reported. Is there an issue with % being used above?

**Comment by taylorza** [comment]
Thanks for reporting the issue, there was indeed a parsing error that I recently introduced. That has been fixed.

As for the second issue, to use binary numbers you can use the `b` suffix. I have fixed the error reported to indicate an "expression error" rather than "divide by zero" which was incorrect.

The following should work now
```
LD BC, 0DDEh
IN A, (C)
AND 00000010b
JR Z, SUBROUTINE
```
Latest version can be downloaded from: https://taylorza.itch.io/nextbasic-inline-assembler

**Comment by nic24-rgb** [comment]
Much appreciated!
